# Name of the workflow as it appears in the GitHub Actions UI
name: API Automation CI

# Controls when the workflow will run
on:
  push:
    branches: [ "main", "dev" ] # Triggers the workflow on pushes to the 'main' and 'develop' branches
  pull_request:
    branches: [ "main", "dev" ] # Triggers the workflow on pull requests targeting 'main' and 'develop'

# Defines a single job in the workflow
jobs:
  build_and_test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest # You can also use windows-latest or macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4 # Action to check out your repository code

    # --- STEPS TO SET UP AND RUN FASTAPI APPLICATION ---

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9' # IMPORTANT: Match your FastAPI app's Python version

    - name: Install FastAPI App Dependencies
      run: |
        pwd # Print the current working directory for debugging
        ls -la # List files in the current directory for debugging
        # Navigate to the FastAPI application's directory
        cd backend-app-setup/bookstore
        pwd # Print the current working directory again to confirm navigation
        ls -la # List files in the FastAPI app directory to confirm presence of requirements.txt
        pip install -r requirements.txt # Make sure this file exists in your FastAPI app folder
      timeout-minutes: 5

    - name: Start FastAPI Application in background
      run: |
        # Navigate to the FastAPI application's directory again
        cd fastapi-backend-app/bookstore/bookstore
        uvicorn main:app --reload
        sleep 15
      timeout-minutes: 2

    # --- STEPS FOR JAVA MAVEN TESTS ---
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4 # Action to set up a Java environment
      with:
        java-version: '17' # Specify the Java version matching your project
        distribution: 'temurin' # Recommended distribution
        cache: maven # Caches Maven dependencies to speed up builds

    - name: Build Project and Run Integration Tests
      # This step will:
      # - Clean the project (mvn clean)
      # - Install dependencies and compile code (mvn install)
      # - Run all TestNG tests (mvn install automatically runs tests if configured via surefire/failsafe plugins)
      # TestNG tests are typically considered integration tests in an API automation context.
      run: mvn -B clean install

    - name: Upload Test Reports
      # This step will always run, even if previous steps fail.
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: Test-Reports
        # Paths are now relative to the repository root directly
        path: |
          target/surefire-reports/*.html # Surefire report here
          reports/ # ExtentReports generated here
        retention-days: 7